# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'TIXNGODemo' do
    # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'sdk', :git => 'https://github.com/tixngo-mobile-github/tixngo_sdk_ios.git', :tag => '1.0.16'
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'
  pod 'AWSCore'
  pod 'AWSCognitoIdentityProvider'
  pod 'SwiftRandom'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.2'
        end
  end
end
